version: "3.7"

services:

    db:
        build: "./db"
        command: --default-authentication-plugin=mysql_native_password
        container_name: db
        restart: always
        environment:
            - MYSQL_DATABASE=argos
            - MYSQL_ROOT_PASSWORD=argos
        volumes:
            - ./db/data:/var/lib/mysql
            - ./db:/docker-entrypoint-initdb.d

    broker:
        build: "./broker"
        container_name: broker
        restart: always
        ports:
            - "1883:1883"

    api:
        build: "./api"
        container_name: api
        restart: always
        volumes:
            - ./api:/home/node/app
        ports:
            - "9001:9001"
        depends_on:
            - broker
            - db

    web:
        build: "./website"
        container_name: website
        restart: always
        volumes:
            - ./website:/var/www/html
        ports:
            - "8888:80"
        depends_on:
            - broker
            - api
            - db
